showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true
fontFamily: 更纱黑体 UI SC # https://github.com/adobe-fonts/source-han-serif/
showNotifications: false
theme: 0
editor: 0
mixinText: |-
  mixin: # object
    dns:
      default-nameserver:
        - 119.29.29.29
        - 114.114.114.114
      enable: true
      enhanced-mode: fake-ip
      nameserver:
        - 114.114.114.114
        - 223.5.5.5
        - 8.8.8.8
      fallback: []
      fake-ip-filter:
        - +.stun.*.*
        - +.stun.*.*.*
        - +.stun.*.*.*.*
        - +.stun.*.*.*.*.*
        - "*.n.n.srv.nintendo.net"
        - +.stun.playstation.net
        - xbox.*.*.microsoft.com
        - "*.*.xboxlive.com"
        - "*.msftncsi.com"
        - "*.msftconnecttest.com"
        - WORKGROUP
