version: '3.9'

services:
    rsshub:
        # two ways to enable puppeteer:
        # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
        # * (consumes more disk space and memory) leave everything unchanged
        image: diygod/rsshub:chromium-bundled
        restart: always
        ports:
            - '127.0.0.1:1200:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PROXY_URI: 'socks5h://warp-socks:9091'
        depends_on:
            - redis

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data

    warp-socks:
        image: monius/docker-warp-socks:latest
        privileged: true
        restart: always
        volumes:
            - /lib/modules:/lib/modules
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0
            net.ipv4.conf.all.src_valid_mark: 1
        healthcheck:
            test: ["CMD", "curl", "-f", "https://www.cloudflare.com/cdn-cgi/trace"]
            interval: 30s
            timeout: 10s
            retries: 5




    miniflux:
      image: miniflux/miniflux
      container_name: miniflux
      restart: always
      ports:
        - "127.0.0.1:8080:8080"
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
        - RUN_MIGRATIONS=1
        - CREATE_ADMIN=1
        - ADMIN_USERNAME=admin
        - ADMIN_PASSWORD=admin_password
        - DEBUG=1
      # Optional health check:
      # healthcheck:
      #  test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
    db:
      image: postgres:15
      container_name: postgres
      environment:
        - POSTGRES_USER=miniflux
        - POSTGRES_PASSWORD=secret
      #  - POSTGRES_DB=miniflux
      volumes:
        - miniflux-db:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "miniflux"]
        interval: 10s
        start_period: 30s
