name: Publish

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup
        run: |
          git clone https://github.com/jackyzha0/quartz
          cp -r quartz/assets assets
          cp -r quartz/i18n i18n
          cp -r quartz/layouts layouts
          cp -r quartz/static static
          cp quartz/.hugo_build.lock .
          cp quartz/.prettierrc .
          cp quartz/Makefile .

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.20
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public --functions=functions -p
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}